name: Daily Economic Calendar Bot

on:
  schedule:
    - cron: "0 6 * * *"  # اجرای خودکار هر روز ساعت 06:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python te_calendar_to_telegram.py
        env:
          TE_API_KEY: ${{ secrets.TE_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
